global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s

  - job_name: 'python-dashboards'
    static_configs:
      - targets: ['python-dashboards:8050']
    scrape_interval: 30s

  - job_name: 'upstash-exporter'
    static_configs:
      - targets: ['upstash-exporter:9101']
    scrape_interval: 30s
